services:
  backend:
    build: ./backend
    container_name: seguidores-backend
    restart: unless-stopped
    # El puerto interno 3000 se expone también al host por si quieres probar la API directamente
    ports:
      - "3800:3000"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  frontend:
    build: ./frontend
    container_name: seguidores-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "2807:80"
