services:
  backend:
    build: ./backend
    container_name: seguidores-backend
    restart: unless-stopped
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
  frontend:
    build: ./frontend
    container_name: seguidores-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
